$RNFirebaseAsStaticFramework = true

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!
use_modular_headers!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'shreemaryda_mobile' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Fix iOS build issues with Firebase and dependencies
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'

        # Fix header search paths for various pods
        config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) ${PODS_ROOT}/leveldb-library'

        # Disable module map for gRPC if it causes issues
        if target.name.include?('gRPC')
          config.build_settings['USE_HEADERMAP'] = 'NO'
        end
      end
    end

    # Fix gRPC module map path issue
    grpc_modulemap_src = "#{installer.sandbox.root}/Target Support Files/gRPC-Core/gRPC-Core.modulemap"
    grpc_modulemap_dst = "#{installer.sandbox.root}/Headers/Private/grpc/gRPC-Core.modulemap"
    if File.exist?(grpc_modulemap_src)
      FileUtils.mkdir_p(File.dirname(grpc_modulemap_dst))
      FileUtils.rm_f(grpc_modulemap_dst)
      FileUtils.cp(grpc_modulemap_src, grpc_modulemap_dst)
    end
  end
end
